services:
  music-bot:
    tty: true
    build:
      context: .
      dockerfile : docker/Dockerfile
    
    env_file:
      - .env 
    image: music-bot:v1
    container_name: music-bot
    volumes:
      - .:/home/music-bot