services:
  music-bot:
    tty: true
    build:
      context: .
      dockerfile : docker/Dockerfile
    
    env_file:
      - .env 
    container_name: music-bot
    volumes:
      - type: bind
        source: .
        target: /home/music-bot/